[workspace]
members = [
  "ostiarius-client",
  "ostiarius-core",
  "ostiarius-server",
]

[workspace.package]
version = "0.4.0"
authors = ["Eric Le Bihan <eric.le.bihan.dev@free.fr>"]
edition = "2021"
license = "MIT"
rust-version = "1.64"
